### ISSUE TITLE
Coordinates of the inner solar system

### ISSUE THREAD

**Issue by mifriis** [mifriis/edge-of-kuiper#15]
We need to be able to calculate distances between planets to enable travel between them.

* [x] All inner planets (mercury -> jupiter)
* [x] Circular orbit (eccentricity 1)
* [x] Distance from sun is their average
* [x] Orbital time their average
* [x] Start position 1/1-2078 (game start) approximated
* [x] Possible to get the coordinate (heliocentric, as in the sun as center, and not geocentric as in when we look up in the sky from our back yard)
* [x] Possible to calculate distance between them

I made this example a couple of years ago: https://codepen.io/asgnoir/pen/GyWXYO using this javascript: https://github.com/lizard-isana/orb.js a lot more advanced than we need it to be though.

**Comment by Nicoolai** [comment]
I'll take a shot at this.
I'll base it on very rough estimates.
