### ISSUE TITLE
A nice way to listen and find commands

### ISSUE THREAD

**Issue by mifriis** [mifriis/edge-of-kuiper#3]
The current switch will soon be hard to understand and there will no doubt be a need for multiple input params in one command

See: https://github.com/mifriis/edge-of-kuiper/blob/main/Systems/CaptainsConsole.cs#L19

**Comment by VisualBean** [comment]
Id actually like to take a stab at this.

**Comment by mifriis** [comment]
I love it @VisualBean !

I have assigned you to the issue.
